### ISSUE TITLE
HTTPS -> HTTP redirect

### ISSUE THREAD

**Issue by nixxquality** [seanbutnotheard/multistream#14]
If you visit https://www.multistre.am/ you get redirected to http://multistre.am/

Something up with your config?

**Comment by seanbutnotheard** [comment]
HTTPS access apppears to be working now. Not sure what the issue was (probably a cloudflare glitch).

**Comment by seanbutnotheard** [comment]
Oh there is one remaining glitch related to this actually... the "following" feature is broken because the url registered with Twitch is http:// rather than https:// and authentication fails. I'll probably just make https:// the default to get around this.
