### ISSUE TITLE
reload button broken?

### ISSUE THREAD

**Issue by neyel8r** [seanbutnotheard/multistream#8]
not sure why but the reload button that is at the right side of the overlay which appears after moving the mouse toward the top of the video has never seemed to do anything for me

**Comment by seanbutnotheard** [comment]
You are correct! The reload button is still coded to work with the old player, I had completely forgotten to update it. That'll be an easy fix.

**Comment by seanbutnotheard** [comment]
Fixed in https://github.com/seanbutnotheard/multistream/commit/4c6d5fba565aedccb14bc7e55747434066aa24a3
